authors:
  timotheus_bodt:
    name: Timotheus Bodt
    description: Principal Investigator
    avatar: assets/images/authors/timotheus_bodt.png
    slug: timotheus_bodt
    url: https://www.tcd.ie/Asian/people/bodtt/

  dasho_karma_ura:
    name: Dasho Karma Ura
    description: Senior Researcher
    avatar: assets/images/authors/dasho_karma_ura.jpg
    slug: dasho_karma_ura
    url: https://bhutanstudies.org.bt/pages/about-us/team-members/

  michael_bayona:
    name: Michael Bayona
    description: Researcher
    avatar: assets/images/authors/michael_bayona.jpg
    slug: michael_bayona
    url: https://github.com/mgarbayona

  rinchen_wangdi:
    name: Rinchen Wangdi
    description: Researcher
    avatar: assets/images/authors/rinchen_wangdi.jpg
    slug: rinchen_wangdi
    # url: 
  
  sonam_lhamo:
    name: Sonam Lhamo
    description: Researcher
    avatar: assets/images/authors/sonam_lhamo.jpg
    slug: sonam_lhamo
    # url: 

  tshering_om_tamang:
    name: Tshering Om Tamang
    description: Researcher
    avatar: assets/images/authors/tshering_om_tamang.jpg
    slug: tshering_om_tamang
    # url:
